{% set name = "medigan" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/medigan-{{ version }}.tar.gz
  sha256: a53b358234c7d635ce92988023f641d3652ebab40862edbb49fa2477e85b51fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - pygithub
    - python >=3.6
    - requests
    - pytorch
    - tqdm

test:
  imports:
    - medigan
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RichardObi/medigan
  summary: medigan is a modular open-source Python library that provides an interface to multiple generative models and automates synthetic dataset generation.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
